### ISSUE TITLE
Missing revisions

### ISSUE THREAD

**Issue by EXSabin** [ajefr/CPS2_Modchip#1]
Hello ajefr!

First and foremost, congratulations for your amazing work and thank you very much for sharing this solution with the community.

I'd like to contribute with some requests. I noticed there are some revisions missing from the HEX files list, namely:

- armwarar1 - Armored Warriors (Asia 940920)
- armwaru - Armored Warriors (USA 941024)
- ddsomar1 - Dungeons & Dragons: Shadow over Mystara (Asia 960208)
- ddsomjr2 - Dungeons & Dragons: Shadow over Mystara (Japan 960223)
- hsf2j1 - Hyper Street Fighter II: The Anniversary Edition (Japan 031222)
- mmancp2ur1 - Mega Man: The Power Battle (CPS2, USA 950926, SAMPLE Version)
- mshbr1 - Marvel Super Heroes (Brazil 951024)
- ringdesth - Ring of Destruction: Slammasters II (Hispanic 940902)
- sfa3us - Street Fighter Alpha 3 (USA 980616
- spf2tu - Super Puzzle Fighter II Turbo (USA 960620)
- ssf2r1 - Super Street Fighter II: The New Challengers (World 930911)
- ssf2tbj1 - Super Street Fighter II: The Tournament Battle (Japan 930911)
- ssf2th - Super Street Fighter II Turbo (Hispanic 940223)
- ssf2xjr1r - Super Street Fighter II X: Grand Master Challenge (Japan 940223 rent version)
- xmvsfjr3 - X-Men Vs. Street Fighter (Japan 960909)
- xmvsfur2 - X-Men Vs. Street Fighter (USA 960910)

I noticed it because I needed "ringdesth" and couldn't find it, so I decided to compare and make a comprehensive list. I tried checking the HEX files on an editor to see if I could edit them myself with the decryption keys from MAME, but couldn't figure out a pattern. Would it be possible for you to make HEX files for these missing revisions and add them to the github as well?

Additionally, if you want to do a small clean-up of the README.md file, I found some possibly unnecessary revisions on the romset table:

- gigaman2 - Giga Man 2: The Power Fighters (bootleg of Mega Man 2: The Power Fighters)
- xmcotar1d - X-Men: Children of the Atom (Euro 950105 Phoenix Edition) (bootleg)
- xmvsfu1d - X-Men Vs. Street Fighter (USA 961004 Phoenix Edition) (bootleg)

Again, thank you for the amazing work. I hope this request can help more people.

Best,

EXSabin

**Comment by ajefr** [comment]
Just upload missing files ;-)

**Comment by EXSabin** [comment]
Many, many thanks!
