### ISSUE TITLE
Pic Key Armored Warriors Brazil

### ISSUE THREAD

**Issue by walgarants** [ajefr/CPS2_Modchip#3]
[armwarb.key.zip](https://github.com/ajefr/CPS2_Modchip/files/7062274/armwarb.key.zip)
Hello friend once again I ask for your help with Pic Key brazil region of armored warriors.
We got a copy of this brazilian game and would like to revive it with your beautiful work.Thanks man

**Comment by ajefr** [comment]
File uploaded !

**Comment by walgarants** [comment]
thank you very much friend

Em ter., 2 de nov. de 2021 às 16:51, ajefr ***@***.***>
escreveu:
